# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  elasticsearch-node1:
    image: docker.io/bitnami/elasticsearch:latest
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node1
      - ELASTICSEARCH_HEAP_SIZE=1g
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_node1_data:/bitnami'

  elasticsearch-node2:
    image: docker.io/bitnami/elasticsearch:latest
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node2
      - ELASTICSEARCH_HEAP_SIZE=1g
    volumes:
      - 'elasticsearch_node2_data:/bitnami'

  elasticsearch-node3:
    image: docker.io/bitnami/elasticsearch:latest
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node3
      - ELASTICSEARCH_HEAP_SIZE=1g
    volumes:
      - 'elasticsearch_node3_data:/bitnami'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-node1:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-node1

volumes:
  elasticsearch_node1_data:
    driver: local
  elasticsearch_node2_data:
    driver: local
  elasticsearch_node3_data:
    driver: local
